services:
  api01: &api
      build:
        context: .
        target: prod
      hostname: api01
      environment:
        - APP_PORT=8080
        - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
        - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
        - POSTGRES_DATABASE_HOSTNAME=${DATABASE_HOSTNAME}
        - POSTGRES_DATABASE_PASSWORD=${DATABASE_PASSWORD}
        - POSTGRES_DATABASE_USER=${DATABASE_USER}
        - POSTGRES_DATABASE_NAME=${DATABASE_NAME}
        - POSTGRES_DATABASE_PORT=5432
      networks:
        - rinha
        - payment-processor
      depends_on:
        - postgres-db
      deploy:
        resources:
          limits:
            cpus: "0.25"
            memory: "100MB"
  api02:
      <<: *api
      hostname: api02
      environment:
        - APP_PORT=8080
        - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
        - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
        - POSTGRES_DATABASE_HOSTNAME=${DATABASE_HOSTNAME}
        - POSTGRES_DATABASE_PASSWORD=${DATABASE_PASSWORD}
        - POSTGRES_DATABASE_USER=${DATABASE_USER}
        - POSTGRES_DATABASE_NAME=${DATABASE_NAME}
        - POSTGRES_DATABASE_PORT=5432

  nginx:
      image: nginx:1.25-alpine
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
      depends_on:
        - api01
        - api02
      networks:
        - rinha
        - payment-processor
      ports:
        # Obrigatório expor/usar a porta 9999 no load balancer!
        - '9999:9999'
      deploy:
        resources:
          limits:
            cpus: '0.1'
            memory: '30MB'

  postgres-db:
      image: postgres:17-alpine
      restart: always
      hostname: ${DATABASE_HOSTNAME}
      environment:
        - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
        - POSTGRES_USER=${DATABASE_USER}
        - POSTGRES_DB=${DATABASE_NAME}
      volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/script.sql
      networks:
        - rinha
        - payment-processor
      deploy:
        resources:
          limits:
            cpus: '0.9'
            memory: '120MB'

volumes:
  postgres_data:

networks:
  payment-processor:
    external: true
  rinha:
    driver: bridge

