services:
  api01: &api
    image: 'api-rinha-de-backend-2025'
    build: 
      context: .
      target: dev
    volumes:
      - .:/app
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "500MB"
  api02:
    <<: *api

  postgres:
    ports:
      - "5432:5432"

  asynqmon:
    image: hibiken/asynqmon
    platform: linux/amd64
    container_name: asynqmon
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - rinha
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - REDIS_ADDR=${REDIS_URL}
