name: 🔖 Tag and release  

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: go-semantic-release/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-and-push-docker-image:
    runs-on: ubuntu-latest
    needs: tag
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up .env file from secrets
        run: cp .env.example .env

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v5.1.0
        with:
          context: .
          push: true
          file: ./Dockerfile
          target: prod
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/emiliosheinz/rinha-de-backend-2025-go:${{ github.ref_name }}
            ghcr.io/emiliosheinz/rinha-de-backend-2025-go:latest
